/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h> //NULL 定义在这个文件
/* Header for class cn_dennishucd_FFmpegNative */

#ifndef _Included_cn_dennishucd_FFmpegNative
#define _Included_cn_dennishucd_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dennishucd_FFmpegNative
 * Method:    avcodec_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegNative_avcodec_1find_1decoder(
		JNIEnv * env, jobject obj, jint codecID) {
//	AVCodec *codec = NULL;
//
//	/*register all formats and codecs */
//	av_register_all();
//
//	codec = avcodec_find_decoder(codecID);
//
//	if (codec != NULL) {
//		return 0;
//	} else {
//		return -1;
//	}

	return codecID;
}

#ifdef __cplusplus
}
#endif
#endif
